services:

  backend:
    build:
      context: .
      dockerfile: EnterpriseAIHelpdesk.API/Dockerfile
    container_name: enterprise-helpdesk-api
    ports:
      - "5244:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=enterprise-helpdesk-sql,1433;Database=EnterpriseAIHelpdeskDB;User Id=HelpdeskApp;Password=YOUR_DB_PASSWORD;TrustServerCertificate=True;MultipleActiveResultSets=true"
      Ollama__Url: "http://host.docker.internal:11434"
    networks:
      - enterprise-helpdesk-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: enterprise-helpdesk-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - enterprise-helpdesk-network

networks:
  enterprise-helpdesk-network:
    external: true