<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnterpriseAIHelpdesk.Application\EnterpriseAIHelpdesk.Application.csproj" />
    <ProjectReference Include="..\EnterpriseAIHelpdesk.Domain\EnterpriseAIHelpdesk.Domain.csproj" />
    <ProjectReference Include="..\EnterpriseAIHelpdesk.Persistence\EnterpriseAIHelpdesk.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.0" />
  </ItemGroup>

</Project>